Repository RHeavenStudio/HeavenStudio, pull requests merged in 2024-01, with the labels that each got.

#661 [style] Update README.md (test new action)
  README.md
Labels: patches

#663 run source generator to add totem climb
  Assets/Scripts/USG.g/LoadMinigames.Minigames.MinigameLoaderGenerator.g.cs
Labels: release-2, minigame

#669 Update Credits.txt
  Assets/Resources/Credits.txt
Labels: release-2
