Repository RHeavenStudio/HeavenStudio, pull requests merged in 2024-02, with the labels that each got.

#673 Kitties Fix
  Assets/Resources/Games/kitties.prefab
  Assets/Resources/Sprites/Games/Kitties/Animations/CaughtSuccess.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/Clap1.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/FaceClap.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/FaceClapFail.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/FaceFailNewIdle.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/FaceNewIdle.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/RollStart.anim
  Assets/Resources/Sprites/Games/Kitties/Animations/Rolling.anim
  Assets/Resources/Sprites/Games/Kitties/kittiesSprites.png
Labels: release-1, patches

#675 Upbeat blip length
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/MrUpbeat/UpbeatMan.cs
Labels: release-1, patches

#679 JSL-Related Improvements
  Assets/Plugins/JoyShockLibrary/JoyShockLibrary.cs
  Assets/Plugins/JoyShockLibrary/Plugins/JoyShockLibrary.dll
  Assets/Plugins/JoyShockLibrary/Plugins/JoyShockLibrary.h
  Assets/Plugins/JoyShockLibrary/Plugins/libJoyShockLibrary.dylib
  Assets/Plugins/JoyShockLibrary/Plugins/libJoyShockLibrary.so
  Assets/Resources/Prefabs/Editor/SettingsMenu/ControllerSetup.prefab
  Assets/Scripts/InputSystem/ControllerTypes/InputJoyconPair.cs
  Assets/Scripts/InputSystem/ControllerTypes/InputJoyconPair.cs.meta
  Assets/Scripts/InputSystem/ControllerTypes/InputJoyshock.cs
  Assets/Scripts/InputSystem/ControllerTypes/InputKeyboard.cs
  Assets/Scripts/InputSystem/ControllerTypes/InputMouse.cs
  Assets/Scripts/InputSystem/InputController.cs
  Assets/Scripts/InputSystem/USG.g/InitInputControllers.PlayerInput.ControllerLoaderGenerator.g.cs
  Assets/Scripts/LevelEditor/EditorTheme.cs
  Assets/Scripts/PersistentDataManager.cs
  Assets/Scripts/SourceGenerators/ControllerLoaderGenerator.cs
  Assets/Scripts/SourceGenerators/MinigameLoaderGenerator.cs
  Assets/Scripts/TitleManager.cs
  Assets/Scripts/UI/SettingsDialog/Tabs/ControllerSettings.cs
  Assets/Scripts/USG.g/LoadMinigames.Minigames.MinigameLoaderGenerator.g.cs
Labels: release-1, patches

#681 fork lifter burger fix
  Assets/Scripts/Games/ForkLifter/ForkLifter.cs
  Assets/Scripts/Games/ForkLifter/ForkLifterPlayer.cs
  Assets/Scripts/Games/ForkLifter/Pea.cs
Labels: release-1, patches

#689 Two new totem climb sounds
  Assets/Resources/Sfx/games/totemClimb/beatchange.wav
  Assets/Resources/Sfx/games/totemClimb/chargejump.wav
Labels: release-2, minigame

#696 Boing Updater + Enum Fix
  Assets/Scripts/Games/Manzai/Manzai.cs
Labels: enhancement, release-2, minigame

#703 Updated the Modified Kurokane Font (again)
  Assets/Resources/Fonts/kurokane/FOT-KurokaneStd_Megamix_Modified-EB.otf
Labels: patches

#718 Rhythm Test GBA Hotfixes (Right Branch Editon!)
  Assets/Resources/Games/rhythmTestGBA.prefab
  Assets/Resources/Sprites/Games/RhythmTestGBA/Button_Practice_Upscale.png
  Assets/Resources/Sprites/Games/RhythmTestGBA/Button_Practice_Upscale.png.meta
  Assets/Scripts/Games/RhythmTestGBA/RhythmTestGBA.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-2, minigame

#720 Advanced Blocks
  Assets/Resources/Prefabs/Editor/EventProperties.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Boolean.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Boolean.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Button.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Button.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Color.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Color.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Dropdown.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Dropdown.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Float.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Float.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Integer.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Integer.prefab.meta
  Assets/Resources/Prefabs/Editor/EventProperties/String.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/String.prefab.meta
  Assets/Resources/Prefabs/Editor/SettingsMenu/EditorSettings.prefab
  Assets/Resources/Prefabs/Editor/SettingsMenu/GameSettings.prefab
  Assets/Resources/Sprites/Editor/GameIcons/advanced.png
  Assets/Resources/Sprites/Editor/GameIcons/advanced.png.meta
  Assets/Resources/Sprites/Editor/GameIcons/advanced_mask.png
  Assets/Resources/Sprites/Editor/GameIcons/advanced_mask.png.meta
  Assets/Scenes/Editor.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Games/SoundEffects.cs
  Assets/Scripts/LevelEditor/Commands/Block.cs
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/BoolPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ButtonPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ButtonPropertyPrefab.cs.meta
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ColorPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/DropdownPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/DropdownPropertyPrefab.cs.meta
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/EnumPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/StringPropertyPrefab.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/LevelEditor/Timeline/TimelineEventObj.cs
  Assets/Scripts/LevelEditor/Tooltip.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/PersistentDataManager.cs
  Assets/Scripts/UI/SettingsDialog/Tabs/EditorSettings.cs
  Assets/Scripts/Util/EntityTypes.cs
  Assets/Scripts/Util/MultiSound.cs
  Assets/Scripts/Util/SoundByte.cs
Labels: enhancement, release-1

#722 mssing semicolon
  Assets/Scripts/Games/BonOdori/BonOdori.cs
Labels: release-2, minigame
