Repository RHeavenStudio/HeavenStudio, pull requests merged in 2024-05, with the labels that each got.

#903 Swing UI and other stuff
  Assets/Scenes/Editor.unity
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/SpecialTimeline.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TempoDialog.cs
Labels: release-1, patches

#908 Swing UI and other stuff
  Assets/Scenes/Editor.unity
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/SpecialTimeline.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TempoDialog.cs
Labels: release-1, patches

#911 Editor Refresh (R1)
  Assets/Resources/Fonts/rodin/FOT-Rodin Pro B SDF Game Title.mat
  Assets/Resources/Fonts/rodin/FOT-Rodin Pro B SDF Game Title.mat.meta
  Assets/Resources/Prefabs/Editor/WindowTemplate.prefab
  Assets/Resources/Prefabs/Editor/WindowTemplate.prefab.meta
  Assets/Resources/Sprites/Editor/UI/Animations/Button.controller
  Assets/Resources/Sprites/Editor/UI/Animations/Button.controller.meta
  Assets/Resources/Sprites/Editor/UI/Playhead.png
  Assets/Resources/Sprites/Editor/UI/Playhead.png.meta
  Assets/Resources/Sprites/Editor/UI/icons/clock.png
  Assets/Resources/Sprites/Editor/UI/icons/sort.png
  Assets/Resources/Sprites/Editor/UI/icons/usage.png
  Assets/Resources/Sprites/Editor/UI/icons/usage.png.meta
  Assets/Resources/Sprites/Editor/UI/icons/zoom-menu.png
  Assets/Resources/Sprites/Editor/UI/icons/zoom-menu.png.meta
  Assets/Resources/Sprites/Editor/UI/icons_atlas.spriteatlas
  Assets/Resources/Sprites/Editor/UI/tap.png
  Assets/Scenes/Editor.unity
  Assets/Scripts/EventCaller.cs
  Assets/Scripts/Games/Tambourine/Tambourine.cs
  Assets/Scripts/InputSystem/ControllerTypes/InputKeyboard.cs
  Assets/Scripts/LevelEditor/DialogHelpers/Dialog.cs
  Assets/Scripts/LevelEditor/Editor.cs
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/EventSelector/GridGameSelector.cs
  Assets/Scripts/LevelEditor/EventSelector/GridGameSelectorGame.cs
  Assets/Scripts/LevelEditor/Selections.cs
  Assets/Scripts/LevelEditor/SnapDialog/SnapDialog.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/SpecialTimeline.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TimelineObjs/TempoTimelineObj.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TimelineObjs/VolumeTimelineObj.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/LevelEditor/Timeline/TimelineZoom.cs
  Assets/Scripts/LevelEditor/ZoomDialog.meta
  Assets/Scripts/LevelEditor/ZoomDialog/ZoomDialog.cs
  Assets/Scripts/LevelEditor/ZoomDialog/ZoomDialog.cs.meta
  Assets/Scripts/Minigames.cs
Labels: enhancement, release-1

#914 Cherry-pick #913
  Assets/Scripts/LevelEditor/Editor.cs
Labels: release-1, patches

#919 Folder Metadata Fix
  Assets/Resources/Sfx/games/loveLab.meta
Labels: release-2, patches

#920 Love Lab Tweaks + Icon
  Assets/Resources/Games/loveLab.prefab
  Assets/Resources/Sprites/Editor/GameIcons/loveLab.png
  Assets/Resources/Sprites/Editor/GameIcons/loveLab.png.meta
  Assets/Resources/Sprites/Editor/GameIcons/loveLab_mask.png
  Assets/Resources/Sprites/Editor/GameIcons/loveLab_mask.png.meta
  Assets/Resources/Sprites/Games/LoveLab/Animations/GirlBopLeft.anim
  Assets/Resources/Sprites/Games/LoveLab/Animations/GirlBopRight.anim
  Assets/Resources/Sprites/Games/LoveLab/Animations/GuyRightFace.anim
  Assets/Resources/Sprites/Games/LoveLab/Animations/ShakeFlaskUp.anim
  Assets/Resources/Sprites/Games/LoveLab/Animations/ThrowFlask.anim
  Assets/Resources/Sprites/Games/LoveLab/Flask.mat
  Assets/Resources/Sprites/Games/LoveLab/GirlFlask.mat
  Assets/Resources/Sprites/Games/LoveLab/GirlShading.mat
  Assets/Resources/Sprites/Games/LoveLab/GuyShading.mat
  Assets/Resources/Sprites/Games/LoveLab/WeirdFlask.mat
  Assets/Resources/Sprites/Games/LoveLab/WeirdShading.mat
  Assets/Resources/Sprites/Games/LoveLab/daytimebg.png
  Assets/Resources/Sprites/Games/LoveLab/lovelabmain.png
  Assets/Resources/Sprites/Games/LoveLab/lovelabtest.png
Labels: release-2, patches, minigame

#921 Miscellaneous R1 Changes
  Assets/Bundled/Games/DrummingPractice/Prefabs/Drummer.prefab
  Assets/Bundled/Games/DrummingPractice/Sprites/mii_error.png
  Assets/Bundled/Games/DrummingPractice/Sprites/mii_error.png.meta
  Assets/Bundled/Games/SpaceBall/spaceball.prefab
  Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs
  Assets/Scripts/Games/SneakySpirits/SneakySpirits.cs
  Assets/Scripts/Games/Spaceball/Spaceball.cs
  Assets/unity-vhsglitch-master.meta
  Assets/unity-vhsglitch-master/VHSGlitch.unitypackage.meta
Labels: release-1, patches, minigame

#933 whoops
  Assets/Scripts/Games/KarateMan/KarateMan.cs
Labels: release-1, patches

#935 o
  Assets/Scripts/Games/KarateMan/KarateMan.cs
Labels: release-1, patches

#927 ignoreSwing parameter for Multisound and BeatAction
  Assets/Scripts/Games/LaunchParty/LaunchPartyRocket.cs
  Assets/Scripts/Games/Minigame.cs
  Assets/Scripts/Util/BeatAction.cs
  Assets/Scripts/Util/MultiSound.cs
  Assets/Scripts/Util/SoundByte.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-1, patches

#938 fixed blue bear sound bug
  Assets/Scripts/Games/BlueBear/BlueBear.cs
  Assets/Scripts/Util/SoundByte.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-1, patches

#945 Misc Release 1 Customization
  Assets/Bundled/Games/Fireworks/Sprites/bg_gradient.png
  Assets/Bundled/Games/Fireworks/Sprites/bg_gradient.png.meta
  Assets/Bundled/Games/Fireworks/Sprites/city.png
  Assets/Bundled/Games/Fireworks/Sprites/city.png.meta
  Assets/Bundled/Games/Fireworks/fireworks.prefab
  Assets/Bundled/Games/ForkLifter/Sprites/GameSprites.png
  Assets/Bundled/Games/ForkLifter/Sprites/GameSprites.png.meta
  Assets/Bundled/Games/ForkLifter/Sprites/megamixfloor.png
  Assets/Bundled/Games/ForkLifter/Sprites/megamixfloor.png.meta
  Assets/Bundled/Games/ForkLifter/forkLifter.prefab
  Assets/Bundled/Games/SpaceSoccer/Sprites/background.png
  Assets/Bundled/Games/SpaceSoccer/Sprites/kicker_main.mat
  Assets/Bundled/Games/SpaceSoccer/Sprites/kicker_main.mat.meta
  Assets/Bundled/Games/SpaceSoccer/Sprites/kicker_mouth.mat
  Assets/Bundled/Games/SpaceSoccer/Sprites/kicker_mouth.mat.meta
  Assets/Bundled/Games/SpaceSoccer/Sprites/platform_fire.mat
  Assets/Bundled/Games/SpaceSoccer/Sprites/platform_fire.mat.meta
  Assets/Bundled/Games/SpaceSoccer/Sprites/platform_main.mat
  Assets/Bundled/Games/SpaceSoccer/Sprites/platform_main.mat.meta
  Assets/Bundled/Games/SpaceSoccer/Sprites/spaceSoccer_main.png
  Assets/Bundled/Games/SpaceSoccer/Sprites/spaceSoccer_main.png.meta
  Assets/Bundled/Games/SpaceSoccer/spaceSoccer.prefab
  Assets/Bundled/Games/TheDazzles/Sprites/boxexterior.mat
  Assets/Bundled/Games/TheDazzles/Sprites/boxexterior.mat.meta
  Assets/Bundled/Games/TheDazzles/Sprites/boxinterior.mat
  Assets/Bundled/Games/TheDazzles/Sprites/boxinterior.mat.meta
  Assets/Bundled/Games/TheDazzles/Sprites/dazzles.png
  Assets/Bundled/Games/TheDazzles/Sprites/dazzles.png.meta
  Assets/Bundled/Games/TheDazzles/theDazzles.prefab
  Assets/Scripts/Games/Fireworks/Fireworks.cs
  Assets/Scripts/Games/ForkLifter/ForkLifter.cs
  Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
  Assets/Scripts/Games/TheDazzles/TheDazzles.cs
Labels: release-1, patches

#946 Karate Man Tweaks
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/Beat.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/Jab.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/JabNoNuri.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/ManChargeOut.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/ManKick.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/ManReturn.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/NoPose.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/Straight.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/ToReady.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/UpperCut.anim
  Assets/Bundled/Games/KarateMan/Sprites/anime/karateman/UpperCutJump.anim
  Assets/Bundled/Games/KarateMan/Sprites/karateman_main.png
  Assets/Bundled/Games/KarateMan/Sprites/karateman_main.png.meta
  Assets/Bundled/Games/KarateMan/karateman.prefab
Labels: release-1, patches, minigame

#948 Fixed Working Dough Swing
  Assets/Scripts/Games/WorkingDough/BGBall.cs
  Assets/Scripts/Games/WorkingDough/NPCDoughBall.cs
  Assets/Scripts/Games/WorkingDough/PlayerEnterDoughBall.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-1, patches, minigame

#944 Bouncy Road improvements
  Assets/Resources/Sfx/games/bouncyRoad/leftBlank.ogg
  Assets/Resources/Sfx/games/bouncyRoad/leftBlank.ogg.meta
  Assets/Resources/Sfx/games/bouncyRoad/rightBlank.ogg
  Assets/Resources/Sfx/games/bouncyRoad/rightBlank.ogg.meta
  Assets/Scripts/Games/BouncyRoad/Ball.cs
  Assets/Scripts/Games/BouncyRoad/BouncyRoad.cs
Labels: release-2, patches, minigame

#951 Dependencies update
  .github/workflows/cherry-tirage.yml
  .gitignore
  Packages/packages-lock.json
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-1, patches

#954 Catch of the day 20240520
  Assets/Resources/Games/CatchOfTheDay.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/FishSchool.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/FishSchool.prefab.meta
  Assets/Resources/Prefabs/Games/CatchOfTheDay/LakeScene.prefab
  Assets/Resources/Sprites/Editor/GameIcons/catchOfTheDay.png
  Assets/Resources/Sprites/Editor/GameIcons/catchOfTheDay_mask.png
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/Fish1/Fish1_JustM.anim
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/Fish1/Fish1_JustM.anim.meta
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/Fish2/Fish2_JustM.anim
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/Fish2/Fish2_JustM.anim.meta
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/FishAnimator.controller
  Assets/Resources/Sprites/Games/CatchOfTheDay/Texture0.png
  Assets/Resources/Sprites/Games/CatchOfTheDay/Texture0.png.meta
  Assets/Scripts/Games/CatchOfTheDay/CatchOfTheDay.cs
  Assets/Scripts/Games/CatchOfTheDay/LakeScene.cs
Labels: release-2, patches, minigame

#957 Metronome Subdivision and More Snapping Options BUT for real this time:tm:
  Assets/Scenes/Editor.unity
  Assets/Scripts/Conductor.cs
  Assets/Scripts/LevelEditor/SnapDialog/SnapDialog.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/UI/UIButton.cs
  Assets/Scripts/UI/UIButton.cs.meta
Labels: release-1, patches

#962 Frog Hop-fix
  Assets/Resources/Sprites/Games/FrogHop/Animations/SingerFrogAnim.controller
  Assets/Resources/Sprites/Games/FrogHop/Animations/SingerSpinHS.anim
  Assets/Resources/Sprites/Games/FrogHop/Animations/SingerSpinHS.anim.meta
  Assets/Scripts/Games/FrogHop/FrogHop.cs
  Assets/Scripts/Games/FrogHop/ntrFrog.cs
Labels: release-2, patches, minigame
