Repository RHeavenStudio/HeavenStudio, pull requests merged in 2024-03, with the labels that each got.

#735 ColorEase Class
  Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs
  Assets/Scripts/Games/CoinToss/CoinToss.cs
  Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs
  Assets/Scripts/Games/ForkLifter/ForkLifter.cs
  Assets/Scripts/Games/KarateMan/KarateMan.cs
  Assets/Scripts/Games/Kitties/Kitties.cs
  Assets/Scripts/Games/Minigame.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs
  Assets/Scripts/Games/Rockers/Rockers.cs
  Assets/Scripts/Games/SpaceDance/SpaceDance.cs
  Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
  Assets/Scripts/Games/Tambourine/Tambourine.cs
  Assets/Scripts/Games/TossBoys/TossBoys.cs
  Assets/Scripts/Util/MultiSound.cs
Labels: release-1, patches

#738 Remove unused namespace from LumBEARjack
  Assets/Scripts/Games/LumBEARjack/LBJSmallObject.cs
  Assets/Scripts/USG.g/LoadMinigames.Minigames.MinigameLoaderGenerator.g.cs
Labels: release-2, patches, minigame

#741 Cannery Hotfix
  Assets/Scripts/Games/Cannery/Cannery.cs
Labels: release-2, patches, minigame

#745 Hide Rap Men
  Assets/Scripts/Games/RapMen/RapMen.cs
Labels: bug, release-2, patches

#746 Change License Badge on README
  README.md
Labels: release-1, patches

#750 R1.1 Hotfixes
  Assets/Scripts/Games/ForkLifter/ForkLifter.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/SpaceDance/SpaceDance.cs
  Assets/Scripts/Games/Tambourine/Tambourine.cs
Labels: release-1, patches

#758 Samurai Slice Gold Particles
  Assets/Resources/Games/karateman.prefab
  Assets/Resources/Games/samuraiSliceNtr.prefab
  Assets/Resources/Sprites/Games/SamuraiSliceNtr/samurainew.png
  Assets/Scripts/Games/SamuraiSliceNtr/SamuraiSliceNtr.cs
Labels: release-1, patches

#760 Update Credits
  Assets/Resources/Credits.txt
Labels: release-1, patches

#763 gradient color mapping shader
  Assets/Shaders/GradientMap.shader
  Assets/Shaders/GradientMap.shader.meta
Labels: enhancement, release-1

#767 Dog Ninja Rework
  Assets/Resources/Games/dogNinja.prefab
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/BirdAnim.controller
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/BirdAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyIn.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyIn.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyOut.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyOut.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/Idle.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyGlobal.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Bop.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/DogAnim.controller
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/DogAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Prepare.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Prepare.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/PrepareIdle.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/PrepareIdle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceBoth.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/UnPrepare.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/UnPrepare.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffGlobal.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfFallLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfFallRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfFallLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfFallRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/DogNinja_OtherObjects.png.meta
  Assets/Scripts/Games/DogNinja/DogNinja.cs
  Assets/Scripts/Games/DogNinja/SpawnHalves.cs
  Assets/Scripts/Games/DogNinja/ThrowObject.cs
Labels: release-1, patches, minigame

#771 Dog Ninja Rework
  Assets/Resources/Games/dogNinja.prefab
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/BirdAnim.controller
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/BirdAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyIn.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyIn.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyOut.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/FlyOut.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/Idle.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Bird/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyGlobal.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/BarelyRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Bop.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/DogAnim.controller
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/DogAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Prepare.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/Prepare.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/PrepareIdle.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/PrepareIdle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceBoth.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/SliceRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/UnPrepare.anim
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/UnPrepare.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffGlobal.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Dog/WhiffRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/Idle.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfFallLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/LeftHalfFallRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfAnim.controller.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfFallLeft.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/Animation/Halves/RightHalfFallRight.anim.meta
  Assets/Resources/Sprites/Games/DogNinja/DogNinja_OtherObjects.png.meta
  Assets/Scripts/Games/DogNinja/DogNinja.cs
  Assets/Scripts/Games/DogNinja/SpawnHalves.cs
  Assets/Scripts/Games/DogNinja/ThrowObject.cs
Labels: release-1, patches, minigame

#773 Built to Scale New Models + Lighting
  Assets/Resources/Games/builtToScaleDS.prefab
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/Elevator.controller
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/FlyingRod.controller
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/MissParts.controller
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/MovingBlocks.controller
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/PartsHit.anim
  Assets/Resources/Models/Games/BuiltToScaleDS/Animations/Shooter.controller
  Assets/Resources/Models/Games/BuiltToScaleDS/ElevatorWithRod.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/ElevatorWithRod.fbx.meta
  Assets/Resources/Models/Games/BuiltToScaleDS/FlyingRod.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/FlyingRod.fbx.meta
  Assets/Resources/Models/Games/BuiltToScaleDS/HitParts.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/HitParts.fbx.meta
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/Divider.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/Effects/Impact.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/Effects/ImpactFaded.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/Object.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/Shooter.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Bridge.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/GapShadow.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Grid.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/GridPlane.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Lights 1.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Lights 2.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Lights 3.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Lights 4.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Lights.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/Materials/World/Line.mat
  Assets/Resources/Models/Games/BuiltToScaleDS/MissParts.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/MissParts.fbx.meta
  Assets/Resources/Models/Games/BuiltToScaleDS/MovingBlocks.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/MovingBlocks.fbx.meta
  Assets/Resources/Models/Games/BuiltToScaleDS/Shooter.fbx
  Assets/Resources/Models/Games/BuiltToScaleDS/Shooter.fbx.meta
  Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
Labels: release-1, patches, minigame

#776 Another Logo Tweaks
  Assets/Resources/Sprites/UI/Common/Opening/Animations/Idle.anim
  Assets/Resources/Sprites/UI/Common/Opening/Animations/LogoBop.anim
  Assets/Resources/Sprites/UI/Common/Opening/Animations/LogoBop2.anim
Labels: release-1, patches

#781 Dropdown Fixes + TryGetMinigame
  Assets/Scenes/Editor.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/DropdownPropertyPrefab.cs
Labels: enhancement, release-1, patches

#785 New vfx work now!
  Assets/Scripts/AppInfo.cs
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-2, patches

#789 Fix Rockers pitch bend
  Assets/Scripts/Games/Rockers/RockersRocker.cs
Labels: release-1, patches, minigame

#797 Fixed airboarder animations, added miss vocals
  Assets/Resources/Models/Games/Airboarder/neo_airboy.fbx
  Assets/Resources/Sfx/games/airboarder/missvox.wav
  Assets/Resources/Sfx/games/airboarder/missvox.wav.meta
Labels: release-2, patches, minigame

#798 Improve note parameters
  Assets/Resources/Prefabs/Editor/EventProperties/Note.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Note.prefab.meta
  Assets/Resources/Prefabs/Editor/SettingsMenu/EditorSettings.prefab
  Assets/Resources/Sfx/games/builtToScaleDS/PianoPreview.ogg
  Assets/Resources/Sfx/games/builtToScaleDS/PianoPreview.ogg.meta
  Assets/Resources/Sfx/games/gleeClub/WailPreview.wav
  Assets/Resources/Sfx/games/gleeClub/WailPreview.wav.meta
  Assets/Scenes/Editor.unity
  Assets/Scripts/Games/BonOdori/BonOdori.cs
  Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
  Assets/Scripts/Games/GleeClub/GleeClub.cs
  Assets/Scripts/Games/LaunchParty/LaunchParty.cs
  Assets/Scripts/Games/Rockers/Rockers.cs
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs.meta
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/PersistentDataManager.cs
  Assets/Scripts/UI/LeftClickEvent.cs
  Assets/Scripts/UI/LeftClickEvent.cs.meta
  Assets/Scripts/UI/SettingsDialog/Tabs/EditorSettings.cs
  Assets/Scripts/Util/EntityTypes.cs
  Assets/Scripts/Util/Sound.cs
  Assets/Scripts/Util/SoundByte.cs
Labels: enhancement, release-1

#799 Cherry-Pick #798
  Assets/Resources/Prefabs/Editor/EventProperties/Note.prefab
  Assets/Resources/Prefabs/Editor/EventProperties/Note.prefab.meta
  Assets/Resources/Prefabs/Editor/SettingsMenu/EditorSettings.prefab
  Assets/Resources/Sfx/games/builtToScaleDS/PianoPreview.ogg
  Assets/Resources/Sfx/games/builtToScaleDS/PianoPreview.ogg.meta
  Assets/Resources/Sfx/games/gleeClub/WailPreview.wav
  Assets/Resources/Sfx/games/gleeClub/WailPreview.wav.meta
  Assets/Scenes/Editor.unity
  Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
  Assets/Scripts/Games/GleeClub/GleeClub.cs
  Assets/Scripts/Games/LaunchParty/LaunchParty.cs
  Assets/Scripts/Games/Rockers/Rockers.cs
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs.meta
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/PersistentDataManager.cs
  Assets/Scripts/UI/LeftClickEvent.cs
  Assets/Scripts/UI/LeftClickEvent.cs.meta
  Assets/Scripts/UI/SettingsDialog/Tabs/EditorSettings.cs
  Assets/Scripts/Util/EntityTypes.cs
  Assets/Scripts/Util/Sound.cs
  Assets/Scripts/Util/SoundByte.cs
Labels: enhancement, release-1, cherry-pick

#803 Bon odori patch
  Assets/Resources/Fonts/WarioWare/WarioWareIncMerge.ttf
  Assets/Resources/Fonts/WarioWare/WarioWareIncMerge.ttf.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF 1.mat
  Assets/Resources/Fonts/WarioWareIncMerge SDF 1.mat.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF 2.mat
  Assets/Resources/Fonts/WarioWareIncMerge SDF 2.mat.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF 3.mat
  Assets/Resources/Fonts/WarioWareIncMerge SDF 3.mat.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF 4.mat
  Assets/Resources/Fonts/WarioWareIncMerge SDF 4.mat.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF 5.mat
  Assets/Resources/Fonts/WarioWareIncMerge SDF 5.mat.meta
  Assets/Resources/Fonts/WarioWareIncMerge SDF.asset
  Assets/Resources/Fonts/WarioWareIncMerge SDF.asset.meta
  Assets/Resources/Games/bonOdori.prefab
  Assets/Resources/Prefabs/Games/BonOdori.meta
  Assets/Resources/Prefabs/Games/BonOdori/Line.prefab
  Assets/Resources/Prefabs/Games/BonOdori/Line.prefab.meta
  Assets/Resources/Prefabs/Games/BonOdori/LineBlue.prefab
  Assets/Resources/Prefabs/Games/BonOdori/LineBlue.prefab.meta
  Assets/Resources/Sfx/games/bonOdori/clap2.wav
  Assets/Resources/Sfx/games/bonOdori/clap2.wav.meta
  Assets/Resources/Sprites/Editor/GameIcons/bonOdori.png.meta
  Assets/Resources/Sprites/Editor/GameIcons/bonOdori_mask.png.meta
  Assets/Resources/Sprites/Games/BonOdori/Animations/Players/CPU.controller
  Assets/Resources/Sprites/Games/BonOdori/Animations/Players/Player.controller
  Assets/Scripts/Games/BonOdori/BonOdori.cs
Labels: release-2, patches, minigame

#806 Built To Scale (Wii) minor fixed
  Assets/Resources/Sprites/Games/BuiltToScaleRvl/Animations/square_left.anim
  Assets/Resources/Sprites/Games/BuiltToScaleRvl/Animations/square_right.anim
  Assets/Resources/Sprites/Games/BuiltToScaleRvl/Animations/square_rotate.anim
  Assets/Resources/Sprites/Games/BuiltToScaleRvl/bts_widget.png.meta
  Assets/Scripts/Games/BuiltToScaleRvl/BuiltToScaleRvl.cs
Labels: release-2, patches, minigame

#810 Catch of the Day fix
  Assets/Scripts/Games/CatchOfTheDay/BGFish.cs
  Assets/Scripts/Games/CatchOfTheDay/LakeScene.cs
Labels: release-2, patches, minigame

#811 chicken hotfixes
  Assets/Scripts/Games/ChargingChicken/ChargingChicken.cs
  Assets/Scripts/Games/ChargingChicken/Island.cs
Labels: release-2, patches, minigame
