Repository RHeavenStudio/HeavenStudio, pull requests merged in 2024-04, with the labels that each got.

#814 Catch of the Day (bugfixes)
  Assets/Resources/Credits.txt
  Assets/Resources/Games/CatchOfTheDay.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/BGFish.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/Bubble.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/LakeScene.prefab
  Assets/Resources/Prefabs/Games/CatchOfTheDay/SchoolFish.prefab
  Assets/Resources/Sprites/Games/CatchOfTheDay/Animations/Fish/FishAnimator.controller
  Assets/Scripts/Games/CatchOfTheDay/BGFish.cs
  Assets/Scripts/Games/CatchOfTheDay/CatchOfTheDay.cs
  Assets/Scripts/Games/CatchOfTheDay/LakeScene.cs
  Assets/Scripts/Minigames.cs
Labels: release-2, patches, minigame

#823 [Freeze Frame] Mostly Bugfixes
  Assets/Resources/Prefabs/Games/FreezeFrame/FarCar.prefab
  Assets/Resources/Prefabs/Games/FreezeFrame/NearCar.prefab
  Assets/Resources/Sprites/Games/FreezeFrame/Animations/NearCar/Idle.anim
  Assets/Scripts/Games/FreezeFrame/Car.cs
  Assets/Scripts/Games/FreezeFrame/Car.cs.meta
  Assets/Scripts/Games/FreezeFrame/FreezeFrame.cs
  Assets/Scripts/Util/ParticleSystemHelpers.cs
Labels: release-2, patches, minigame

#825 Not Again
  Assets/Scripts/Games/CatchOfTheDay/BGFish.cs
Labels: release-2, patches

#827 Auto-Swing
  Assets/Resources/Credits.txt
  Assets/Scenes/Editor.unity
  Assets/Scripts/Conductor.cs
  Assets/Scripts/EventCaller.cs
  Assets/Scripts/GameCamera.cs
  Assets/Scripts/GameInitializer.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Games/BlueBear/Treat.cs
  Assets/Scripts/Games/CatchyTune/Fruit.cs
  Assets/Scripts/Games/CropStomp/Veggie.cs
  Assets/Scripts/Games/DoubleDate/Basketball.cs
  Assets/Scripts/Games/DoubleDate/DoubleDate.cs
  Assets/Scripts/Games/DoubleDate/Football.cs
  Assets/Scripts/Games/DoubleDate/SoccerBall.cs
  Assets/Scripts/Games/FanClub/FanClub.cs
  Assets/Scripts/Games/FanClub/NtrIdolAmie.cs
  Assets/Scripts/Games/FanClub/NtrIdolFan.cs
  Assets/Scripts/Games/KarateMan/KarateMan.cs
  Assets/Scripts/Games/KarateMan/KarateManPot.cs
  Assets/Scripts/Games/Minigame.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/PajamaParty/CtrPillowMonkey.cs
  Assets/Scripts/Games/PajamaParty/CtrPillowPlayer.cs
  Assets/Scripts/Games/PlayerActionEvent.cs
  Assets/Scripts/Games/RhythmTweezers/LongHair.cs
  Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs
  Assets/Scripts/Games/SeeSaw/SeeSawGuy.cs
  Assets/Scripts/Games/SneakySpirits/SneakySpirits.cs
  Assets/Scripts/Games/SpaceSoccer/Ball.cs
  Assets/Scripts/Games/WizardsWaltz/Wizard.cs
  Assets/Scripts/Games/WizardsWaltz/WizardsWaltz.cs
  Assets/Scripts/InputSystem/PlayerInput.cs
  Assets/Scripts/LevelEditor/Editor.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/SpecialTimeline.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TempoDialog.cs
  Assets/Scripts/LevelEditor/Timeline/SpecialTmeline/TimelineObjs/TempoTimelineObj.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/LevelEditor/Timeline/TimelineBlockManager.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/TitleManager.cs
  Assets/Scripts/Util/AnimationHelpers.cs
  Assets/Scripts/Util/MultiSound.cs
  Assets/Scripts/Util/SoundByte.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: enhancement, release-1, patches

#826 Cleaning up those dang warnings
  Assets/Scripts/AppInfo.cs
  Assets/Scripts/Conductor.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Games/Airboarder/Airboarder.cs
  Assets/Scripts/Games/BuiltToScaleRvl/BuiltToScaleRvl.cs
  Assets/Scripts/Games/CatchOfTheDay/BGFish.cs
  Assets/Scripts/Games/CatchOfTheDay/LakeScene.cs
  Assets/Scripts/Games/ChargingChicken/ChargingChicken.cs
  Assets/Scripts/Games/DJSchool/DJSchool.cs
  Assets/Scripts/Games/FanClub/FanClub.cs
  Assets/Scripts/Games/FanClub/NtrIdolAmie.cs
  Assets/Scripts/Games/ForkLifter/ForkLifterPlayer.cs
  Assets/Scripts/Games/Global/Filter.cs
  Assets/Scripts/Games/KarateMan/KarateManJoe.cs
  Assets/Scripts/Games/Kitties/CtrTeppanPlayer.cs
  Assets/Scripts/Games/Manzai/Manzai.cs
  Assets/Scripts/Games/MonkeyWatch/MonkeyWatch.cs
  Assets/Scripts/Games/NailCarpenter/NailCarpenter.cs
  Assets/Scripts/Games/PlayerActionEvent.cs
  Assets/Scripts/Games/RhythmTestGBA/RhythmTestGBA.cs
  Assets/Scripts/Games/SamuraiSliceNtr/NtrSamuraiObject.cs
  Assets/Scripts/Games/SickBeats/Virus.cs
  Assets/Scripts/Games/SpaceSoccer/Kicker.cs
  Assets/Scripts/Games/SumoBrothers/SumoBrothers.cs
  Assets/Scripts/Games/TheDazzles/TheDazzles.cs
  Assets/Scripts/InputSystem/ControllerTypes/InputJoyshock.cs
  Assets/Scripts/LevelEditor/Commands/CommandManager.cs
  Assets/Scripts/LevelEditor/Editor.cs
  Assets/Scripts/LevelEditor/Timeline/TimelineBlockManager.cs
  Assets/Scripts/TitleManager.cs
  Assets/Scripts/Util/SavWav.cs
  Assets/Scripts/Util/SoundByte.cs
  Assets/X-PostProcessing/Effects/ColorAdjustmentLensFilter/ColorAdjustmentLensFilter.cs
  Assets/X-PostProcessing/Effects/ColorAdjustmentTint/ColorAdjustmentTint.cs
  Assets/X-PostProcessing/Effects/ColorReplace/ColorReplace.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionRoberts/EdgeDetectionRoberts.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionRobertsNeon/EdgeDetectionRobertsNeon.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionRobertsNeonV2/EdgeDetectionRobertsNeonV2.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionScharr/EdgeDetectionScharr.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionScharrNeon/EdgeDetectionScharrNeon.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionScharrNeonV2/EdgeDetectionScharrNeonV2.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionSobel/EdgeDetectionSobel.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionSobelNeon/EdgeDetectionSobelNeon.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionSobelNeonV2/EdgeDetectionSobelNeonV2.cs
  Assets/X-PostProcessing/Effects/GlitchDigitalStripe/GlitchDigitalStripe.cs
  Assets/X-PostProcessing/Effects/PixelizeCircle/PixelizeCircle.cs
  Assets/X-PostProcessing/Effects/PixelizeLed/PixelizeLed.cs
  Assets/X-PostProcessing/Effects/PixelizeSector/PixelizeSector.cs
  Assets/X-PostProcessing/Effects/RapidOldTVVignette/RapidOldTVVignette.cs
  Assets/X-PostProcessing/Effects/RapidOldTVVignetteV2/RapidOldTVVignetteV2.cs
  Assets/X-PostProcessing/Effects/RapidVignette/RapidVignette.cs
  Assets/X-PostProcessing/Effects/RapidVignetteV2/RapidVignetteV2.cs
Labels: release-2

#836 Conductor Tweaks
  Assets/Scripts/Conductor.cs
Labels: release-1, patches

#834 Updates to note paramaters + some additional sound fixes (for r2)
  Assets/Bundled/Games/BuiltToScaleDS/Sounds/PianoPreview.ogg
  Assets/Bundled/Games/BuiltToScaleDS/Sounds/PianoPreview.ogg.meta
  Assets/Bundled/Games/GleeClub/Sounds/WailPreview.wav
  Assets/Bundled/Games/GleeClub/Sounds/WailPreview.wav.meta
  Assets/Resources/Prefabs/Editor/EventProperties/Note.prefab
  Assets/Scripts/Games/BoardMeeting/BMExecutive.cs
  Assets/Scripts/Games/BonOdori/BonOdori.cs
  Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
  Assets/Scripts/Games/ChargingChicken/ChargingChicken.cs
  Assets/Scripts/Games/GleeClub/ChorusKid.cs
  Assets/Scripts/Games/GleeClub/GleeClub.cs
  Assets/Scripts/Games/LaunchParty/LaunchParty.cs
  Assets/Scripts/Games/Manzai/Manzai.cs
  Assets/Scripts/Games/RhythmTweezers/LongHair.cs
  Assets/Scripts/Games/Rockers/Rockers.cs
  Assets/Scripts/Games/Rockers/RockersInput.cs
  Assets/Scripts/Games/Rockers/RockersRocker.cs
  Assets/Scripts/Games/SeeSaw/SeeSaw.cs
  Assets/Scripts/Games/SlotMonster/SlotMonster.cs
  Assets/Scripts/Games/Tunnel/Tunnel.cs
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/DropdownPropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/NoteSample.cs
  Assets/Scripts/NoteSample.cs.meta
  Assets/Scripts/Util/EntityTypes.cs
  Assets/Scripts/Util/MultiSound.cs
  Assets/Scripts/Util/Sound.cs
Labels: release-2, patches

#838 Fix the spelling and grammar (Release 1 only)
  Assets/Scripts/Games/AirRally/AirRally.cs
  Assets/Scripts/Games/BlueBear/BlueBear.cs
  Assets/Scripts/Games/CropStomp/CropStomp.cs
  Assets/Scripts/Games/DoubleDate/DoubleDate.cs
  Assets/Scripts/Games/FanClub/FanClub.cs
  Assets/Scripts/Games/Fireworks/Fireworks.cs
  Assets/Scripts/Games/FirstContact/FirstContact.cs
  Assets/Scripts/Games/MarchingOrders/MarchingOrders.cs
  Assets/Scripts/Games/MeatGrinder/MeatGrinder.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/OctopusMachine/OctopusMachine.cs
  Assets/Scripts/Games/SamuraiSliceNtr/SamuraiSliceNtr.cs
  Assets/Scripts/Games/SeeSaw/SeeSaw.cs
  Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
  Assets/Scripts/Games/TapTroupe/TapTroupe.cs
  Assets/Scripts/Minigames.cs
Labels: release-1, patches

#843 Asset Loading Fix
  Assets/Scripts/Conductor.cs
  Assets/Scripts/EventCaller.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
  Assets/Scripts/Games/SneakySpirits/SneakySpirits.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/UI/Overlays/TimingAccuracyDisplay.cs
Labels: release-1, patches

#846 Fix Operation Order Issue in Mr Upbeat
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
Labels: release-1, patches

#845 Made Nail Carpenter Half-Time!
  Assets/Resources/Games/nailCarpenter.prefab
  Assets/Scripts/Games/NailCarpenter/NailCarpenter.cs
Labels: release-2, patches, minigame

#851 let mispacked games skip preload
  Assets/Scripts/Minigames.cs
Labels: release-1, patches

#853 Fixed the parameters for Gaussian Blur, whoopsies
  Assets/Scripts/Minigames.cs
Labels: release-2, patches

#855 Revert "let mispacked games skip preload"
  Assets/Scripts/Minigames.cs
Labels: release-2, patches

#861 Fix Game Asset Loading Issues
  Assets/Scripts/Common/SuperScroll.cs
  Assets/Scripts/Conductor.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/LevelEditor/Commands/Block.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/Minigames.cs
  Assets/Scripts/UI/Overlays/SkillStarManager.cs
  Assets/Scripts/Util/SoundByte.cs
Labels: release-1, patches

#860 Glee Club fix
  Assets/Scripts/Games/GleeClub/GleeClub.cs
  Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NotePropertyPrefab.cs
Labels: release-1, patches

#854 Bouncy Road
  Assets/Resources/Games/bouncyRoad.prefab
  Assets/Resources/Games/bouncyRoad.prefab.meta
  Assets/Resources/Prefabs/Games/BouncyRoad.meta
  Assets/Resources/Prefabs/Games/BouncyRoad/Thing.prefab
  Assets/Resources/Prefabs/Games/BouncyRoad/Thing.prefab.meta
  Assets/Resources/Sfx/games/bouncyRoad.meta
  Assets/Resources/Sfx/games/bouncyRoad/ballBounce.ogg
  Assets/Resources/Sfx/games/bouncyRoad/ballBounce.ogg.meta
  Assets/Resources/Sfx/games/bouncyRoad/ballLeft.ogg
  Assets/Resources/Sfx/games/bouncyRoad/ballLeft.ogg.meta
  Assets/Resources/Sfx/games/bouncyRoad/ballRight.ogg
  Assets/Resources/Sfx/games/bouncyRoad/ballRight.ogg.meta
  Assets/Resources/Sfx/games/bouncyRoad/goal.ogg
  Assets/Resources/Sfx/games/bouncyRoad/goal.ogg.meta
  Assets/Resources/Sprites/Editor/GameIcons/bouncyRoad.png
  Assets/Resources/Sprites/Editor/GameIcons/bouncyRoad.png.meta
  Assets/Resources/Sprites/Games/BouncyRoad.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/A Button Podium Thing.controller
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/A Button Podium Thing.controller.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/A Podium.anim
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/A Podium.anim.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/D-Pad Podium Thing.controller
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/D-Pad Podium Thing.controller.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/D-Pad Podium.anim
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/D-Pad Podium.anim.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/Thing Podium.anim
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/Thing Podium.anim.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/Thing.controller
  Assets/Resources/Sprites/Games/BouncyRoad/Animations/Thing.controller.meta
  Assets/Resources/Sprites/Games/BouncyRoad/Bouncy Road.png
  Assets/Resources/Sprites/Games/BouncyRoad/Bouncy Road.png.meta
  Assets/Scripts/Games/BouncyRoad.meta
  Assets/Scripts/Games/BouncyRoad/Ball.cs
  Assets/Scripts/Games/BouncyRoad/Ball.cs.meta
  Assets/Scripts/Games/BouncyRoad/BouncyRoad.cs
  Assets/Scripts/Games/BouncyRoad/BouncyRoad.cs.meta
  Assets/Scripts/USG.g/LoadMinigames.Minigames.MinigameLoaderGenerator.g.cs
Labels: release-2, minigame

#870 Bouncy Road Tweaks 2
  Assets/Resources/Games/bouncyRoad.prefab
  Assets/Resources/Sprites/Games/BouncyRoad/Bouncy Road.png.meta
  Assets/Scripts/Games/BouncyRoad/BouncyRoad.cs
Labels: release-2, minigame

#871 Chameleon fixed
  Assets/Scripts/Games/Chameleon/Chameleon.cs
Labels: release-2, patches, minigame

#872 Bouncy Road Tweaks 3
  Assets/Resources/Games/bouncyRoad.prefab
Labels: release-2, patches

#874 Added major and minor features to Timeline
  Assets/Scripts/LevelEditor/Commands/Space.cs
  Assets/Scripts/LevelEditor/Commands/Space.cs.meta
  Assets/Scripts/LevelEditor/Editor.cs
  Assets/Scripts/LevelEditor/Timeline/Timeline.cs
  Assets/Scripts/LevelEditor/Timeline/TimelineEventObj.cs
Labels: enhancement, release-1, patches

#876 Fixed Toss Boys Ball Pop Prepare in Touch Mode
  Assets/Scripts/Games/TossBoys/TossBoys.cs
Labels: release-1, patches, minigame

#877 Vignette Spotlight (+ Neon fix)
  Assets/Scenes/Editor.unity
  Assets/Scripts/Minigames.cs
  Assets/Scripts/PostProcessingVFX.cs
  Assets/X-PostProcessing/Effects/EdgeDetectionSobelNeonV2/EdgeDetectionSobelNeonV2.cs
Labels: release-1, patches

#878 Sumo Brothers Bug Fixes + More Customizability
  Assets/Resources/Games/sumoBrothers.prefab
  Assets/Resources/Sprites/Games/SumoBrothers/Animations/SumoBrothers/Heads/SumoGHead.controller
  Assets/Resources/Sprites/Games/SumoBrothers/Animations/SumoBrothers/Heads/SumoGHead.controller.meta
  Assets/Resources/Sprites/Games/SumoBrothers/Animations/SumoBrothers/Heads/SumoPHead.controller
  Assets/Resources/Sprites/Games/SumoBrothers/Animations/SumoBrothers/Heads/SumoPHead.controller.meta
  Assets/Resources/Sprites/Games/SumoBrothers/BGColor.mat
  Assets/Resources/Sprites/Games/SumoBrothers/BGColor.mat.meta
  Assets/Resources/Sprites/Games/SumoBrothers/sumou_bg.png.meta
  Assets/Resources/Sprites/Games/SumoBrothers/sumou_bg_alt.png
  Assets/Resources/Sprites/Games/SumoBrothers/sumou_bg_alt.png.meta
  Assets/Scripts/Games/SumoBrothers/SumoBrothers.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-2, patches, minigame

#881 Color Persistence for Nightly Games
  Assets/Scripts/Games/BasketballGirls/BasketballGirls.cs
  Assets/Scripts/Games/BouncyRoad/BouncyRoad.cs
  Assets/Scripts/Games/Chameleon/Chameleon.cs
  Assets/Scripts/Games/ClapTrap/ClapTrap.cs
  Assets/Scripts/Games/Fillbots/Fillbots.cs
  Assets/Scripts/Games/FrogPrincess/FrogPrincess.cs
  Assets/Scripts/Games/SickBeats/SickBeats.cs
  Assets/Scripts/Games/SumoBrothers/SumoBrothers.cs
Labels: release-2, patches

#882 Color Persistence for R1 games, also fixed Lockstep color bug
  Assets/Scripts/Games/Lockstep/Lockstep.cs
  Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
Labels: release-1, patches

#884 Force Dive for Splashdown
  Assets/Scripts/Games/Splashdown/Splashdown.cs
Labels: release-1, patches

#886 Delayed Property Tooltips
  Assets/Resources/Prefabs/Editor/SettingsMenu/EditorSettings.prefab
  Assets/Resources/Prefabs/GameView/GameTex.renderTexture
  Assets/Resources/Prefabs/GameView/OverlayTex.renderTexture
  Assets/Scenes/Editor.unity
  Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
  Assets/Scripts/LevelEditor/Tooltip.cs
  Assets/Scripts/PersistentDataManager.cs
  Assets/Scripts/UI/SettingsDialog/Tabs/EditorSettings.cs
  ProjectSettings/SatorImaging.UnitySourceGenerator.Editor.ProjectSettingsData.asset
Labels: release-1, patches

#889 Airboarder is now More Recolorable!
  Assets/ColorMask.meta
  Assets/ColorMask/Scenes.meta
  Assets/ColorMask/Scenes/ColorMaskDemoScene.meta
  Assets/ColorMask/Scenes/ColorMaskDemoScene.unity
  Assets/ColorMask/Scenes/ColorMaskDemoScene.unity.meta
  Assets/ColorMask/Scenes/ColorMaskDemoScene/LightmapSnapshot.asset
  Assets/ColorMask/Scenes/ColorMaskDemoScene/LightmapSnapshot.asset.meta
  Assets/ColorMask/Scenes/ColorMaskDemoScene/SkyboxProbe-0.exr
  Assets/ColorMask/Scenes/ColorMaskDemoScene/SkyboxProbe-0.exr.meta
  Assets/ColorMask/Scenes/ColorMaskDemoSceneSettings.lighting
  Assets/ColorMask/Scenes/ColorMaskDemoSceneSettings.lighting.meta
  Assets/ColorMask/Scripts.meta
  Assets/ColorMask/Scripts/MaterialUpdateExample.cs
  Assets/ColorMask/Scripts/MaterialUpdateExample.cs.meta
  Assets/ColorMask/Shaders.meta
  Assets/ColorMask/Shaders/ColorMaskStandard.shader
  Assets/ColorMask/Shaders/ColorMaskStandard.shader.meta
  Assets/ColorMask/Shaders/ColorMaskStandardCore.cginc
  Assets/ColorMask/Shaders/ColorMaskStandardCore.cginc.meta
  Assets/ColorMask/Shaders/ColorMaskStandardCoreForward.cginc
  Assets/ColorMask/Shaders/ColorMaskStandardCoreForward.cginc.meta
  Assets/ColorMask/Shaders/ColorMaskStandardCoreForwardSimple.cginc
  Assets/ColorMask/Shaders/ColorMaskStandardCoreForwardSimple.cginc.meta
  Assets/ColorMask/Shaders/ColorMaskStandardInput.cginc
  Assets/ColorMask/Shaders/ColorMaskStandardInput.cginc.meta
  Assets/ColorMask/Shaders/ColorMaskStandardMeta.cginc
  Assets/ColorMask/Shaders/ColorMaskStandardMeta.cginc.meta
  Assets/ColorMask/Shaders/ColorMaskStandardSpecular.shader
  Assets/ColorMask/Shaders/ColorMaskStandardSpecular.shader.meta
  Assets/ColorMask/Shaders/Editor.meta
  Assets/ColorMask/Shaders/Editor/ColorMaskStandardShaderGUI.cs
  Assets/ColorMask/Shaders/Editor/ColorMaskStandardShaderGUI.cs.meta
  Assets/ColorMask/Textures.meta
  Assets/ColorMask/readme.pdf
  Assets/ColorMask/readme.pdf.meta
  Assets/Resources/Games/airboarder.prefab
  Assets/Resources/Models/Games/Airboarder/Animations/hover.anim
  Assets/Resources/Models/Games/Airboarder/Materials/Dog.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_board.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_body.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_dead.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_shadow.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_shout.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_smile.mat
  Assets/Resources/Models/Games/Airboarder/Materials/block_shadow.mat
  Assets/Resources/Models/Games/Airboarder/Materials/clouds.mat
  Assets/Resources/Models/Games/Airboarder/Materials/dog_shadow.mat
  Assets/Resources/Models/Games/Airboarder/Materials/floorspecular.mat
  Assets/Resources/Models/Games/Airboarder/Materials/mothership.mat
  Assets/Resources/Models/Games/Airboarder/Materials/wall_body.mat
  Assets/Scripts/Games/Airboarder/Airboarder.cs
Labels: release-2, patches, minigame

#891 Fix Chameleon Countin
  Assets/Scripts/Games/Chameleon/Chameleon.cs
Labels: release-2, patches, minigame

#892 More Airboarder visual touchups/fixes
  Assets/Resources/Models/Games/Airboarder/Animations/charge.anim
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_board.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_body.mat
  Assets/Resources/Models/Games/Airboarder/Materials/airboy_smile.mat
  Assets/Resources/Models/Games/Airboarder/Materials/floorspecular.mat
  Assets/Scripts/Games/Airboarder/Airboarder.cs
  Assets/Shaders/SpecularGlow.shader
  Assets/Shaders/SpecularGlow.shader.meta
  Assets/Shaders/SpecularRGB.shader
  Assets/Shaders/SpecularRGB.shader.meta
Labels: release-2, patches, minigame

#893 New Rhythm Test GBA Upscale!
  Assets/Resources/Games/rhythmTestGBA.prefab
  Assets/Resources/Sprites/Games/RhythmTestGBA/Animation/Button/Idle.anim
  Assets/Resources/Sprites/Games/RhythmTestGBA/Animation/Button/Press.anim
  Assets/Resources/Sprites/Games/RhythmTestGBA/Animation/Flash/Idle.anim
  Assets/Resources/Sprites/Games/RhythmTestGBA/Animation/Flash/KTBPulse.anim
  Assets/Resources/Sprites/Games/RhythmTestGBA/RhythmTest.png
  Assets/Resources/Sprites/Games/RhythmTestGBA/RhythmTest.png.meta
  Assets/Scripts/Games/RhythmTestGBA/RhythmTestGBA.cs
Labels: release-2

#895 Pixelize VFX!
  Assets/PostProcessingVFX/GameCameraProfile.asset
  Assets/Resources/Prefabs/GameView/GameTex.renderTexture
  Assets/Resources/Prefabs/GameView/OverlayTex.renderTexture
  Assets/Scenes/Editor.unity
  Assets/Scripts/Minigames.cs
  Assets/Scripts/PostProcessingVFX.cs
  Assets/X-PostProcessing/Effects/PixelizeQuad/PixelizeQuad.cs
Labels: enhancement, release-1, patches
